### ISSUE TITLE
[KV Feedback]: I would like to use KV on a project but it doesn't work? Is there a way to upgrade old projects?

### ISSUE THREAD

**Issue by digitaldesigndj** [denoland/deploy_feedback#477]
### 🔍

- [ ] Did you search for existing issues?

### Type of feedback

Bug report

### Description

I have a deployment videopoker-academy and it errors because OpenKV is not a function.

https://dash.deno.com/projects/videopoker-academy

I had trouble renaming the project it seems that even erasing the project and naming a new one will not activate KV.

**Comment by lucab** [comment]
Thanks for the report.
Deploy KV is currently [in beta](https://deno.com/blog/kv) and behind a waitlist.
I think your account may not yet have access to KV, and in that case you can follow the docs and sign up at https://deno.com/kv (please note that it may take some time to go through the waitlist).

**Comment by piscisaureus** [comment]
@digitaldesigndj 

I've just enabled KV for the `Hyprtxt` organization. It should work now for existing projects, but you might have to create a new deployment.

**Comment by digitaldesigndj** [comment]
I was confused because I put under the org. Thank you nice work

**Comment by digitaldesigndj** [comment]
It's still not working anymore. It has an error that I just cant figure out.

`TypeError: Default database is not available`

I am using fresh-session with kv as the store. It was working on my account before. If you have to wipe the info in the database I really don't care at all.

**Comment by fxnoob** [comment]
I wanted to test out this queue listener feature but it's not working out for my project here: https://dash.deno.com/projects/sps.

Same error message is coming:

```TypeError: Default database is not available```

**Comment by johndevor** [comment]
I am also getting "Default database is not available"
