### ISSUE TITLE
[Bug]: Deno despite successfully submitting task, queues listener isn't called, an error is displayed

### ISSUE THREAD

**Issue by uriva** [denoland/deploy_feedback#720]
### Problem description

Deno despite successfully submitting task, queues listener isn't called, an error is displayed

### Steps to reproduce

https://github.com/denoland/deno/issues/25934

### Expected behavior

the listener should have been called and the log displayed

### Environment

I don't know which version deno deploy runs

**Comment by losfair** [comment]
Hi @uriva ,

Could you check it again? It should be fixed now

**Comment by uriva** [comment]
works thanks

**Comment by MerryOscar** [comment]
I am still seeing this error on Deno v2.1.2

```
Error: txnproxy call timed out
    at async doAtomicWriteInPlace (ext:deno_kv/01_db.ts:629:10)
    at async Kv.enqueue (ext:deno_kv/01_db.ts:163:26)
```

@losfair any ideas?
